# Generated by Django 4.0.2 on 2022-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Discount Code')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Discount start date')),
                ('valid_to', models.DateField(verbose_name='Discount end date')),
                ('discount', models.FloatField(default=0, verbose_name='Discount Precentage')),
                ('discount_type', models.CharField(choices=[('sh', 'shipping'), ('pr', 'price')], default='pr', max_length=2, verbose_name='Discount_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
