# Generated by Django 4.0.2 on 2022-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(verbose_name='Discount start date'),
        ),
    ]
