# Generated by Django 4.0.2 on 2022-07-14 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_optionvalue_is_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('gover', models.CharField(choices=[('an', 'الانبار'), ('ba', 'بابل'), ('bg', 'بغداد'), ('bs', 'البصرة'), ('na', 'الناصرية'), ('di', 'الديوانية'), ('dy', 'ديالى'), ('dh', 'دهوك'), ('er', 'أربيل'), ('ha', 'الحلة'), ('ka', 'كربلاء'), ('ki', 'كركوك'), ('am', 'العمارة'), ('sa', 'السماوة'), ('nj', 'نجف'), ('mo', 'الموصل'), ('sa', 'صلاح الدين'), ('su', 'السليمانية'), ('ku', 'الكوت')], max_length=3, verbose_name='Governorate Name')),
                ('city', models.CharField(max_length=50, verbose_name='City Name')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح.', regex='^(((?:\\+|00)964)|(0)*)7[578]\\d{8}$')], verbose_name='Shipping Phone Number')),
                ('near_point', models.CharField(max_length=50, verbose_name='Nearset Point Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('qty', models.IntegerField(verbose_name='Product Quentity')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.optionvalue', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('order_status', models.CharField(choices=[('re', 'تم استلام الطلب'), ('pre', 'تم تجهيز الطلب'), ('sh', 'تم شحن الطلب'), ('de', 'تم تسليم الطلب')], max_length=50, verbose_name='Order Status')),
                ('ref_code', models.CharField(max_length=11, verbose_name='Order Id')),
                ('items', models.ManyToManyField(to='cart.OrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
