# Generated by Django 4.0.2 on 2022-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('re', 'تم استلام الطلب'), ('pre', 'تم تجهيز الطلب'), ('sh', 'تم شحن الطلب'), ('de', 'تم تسليم الطلب')], default='re', max_length=50, verbose_name='Order Status'),
        ),
    ]
