# Generated by Django 4.0.2 on 2022-07-14 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح.', regex='^(((?:\\+|00)964)|(0)*)7[578]\\d{8}$')], verbose_name='Shipping Phone Number'),
        ),
    ]
