# Generated by Django 4.0.2 on 2022-07-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_optionvalue_is_set'),
        ('cart', '0006_alter_shippinginfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.optionvalue', verbose_name='Product'),
        ),
    ]
