# Generated by Django 4.0.2 on 2022-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Shipping Name'),
        ),
    ]
